server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://82.197.92.72:3306/mmpdb?useSSL=false&allowPublicKeyRetrieval=true
    username: nexuspulse
    password: StrongPassword@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true